export const CURRENCY_LIST = [
    { id: 9, name: "Indian Rupee", code: "INR" },
    { id: 1, name: "United States Dollar", code: "USD" },
    { id: 2, name: "Euro", code: "EUR" },
    { id: 3, name: "British Pound Sterling", code: "GBP" },
    { id: 4, name: "Japanese Yen", code: "JPY" },
    { id: 5, name: "Australian Dollar", code: "AUD" },
    { id: 6, name: "Canadian Dollar", code: "CAD" },
    { id: 7, name: "Swiss Franc", code: "CHF" },
    { id: 8, name: "Chinese Yuan Renminbi", code: "CNY" },
    { id: 10, name: "Brazilian Real", code: "BRL" },
    { id: 11, name: "South African Rand", code: "ZAR" },
    { id: 12, name: "New Zealand Dollar", code: "NZD" },
    { id: 13, name: "Singapore Dollar", code: "SGD" },
    { id: 14, name: "Mexican Peso", code: "MXN" },
    { id: 15, name: "Russian Ruble", code: "RUB" },
    { id: 16, name: "Hong Kong Dollar", code: "HKD" },
    { id: 17, name: "Norwegian Krone", code: "NOK" },
    { id: 18, name: "Swedish Krona", code: "SEK" },
    { id: 19, name: "Danish Krone", code: "DKK" },
    { id: 20, name: "Turkish Lira", code: "TRY" },
    { id: 21, name: "Israeli New Shekel", code: "ILS" },
    { id: 22, name: "Thai Baht", code: "THB" },
    { id: 23, name: "Philippine Peso", code: "PHP" },
    { id: 24, name: "Indonesian Rupiah", code: "IDR" },
    { id: 25, name: "Malaysian Ringgit", code: "MYR" },
    { id: 26, name: "Vietnamese Dong", code: "VND" },
    { id: 27, name: "South Korean Won", code: "KRW" },
    { id: 28, name: "Colombian Peso", code: "COP" },
    { id: 29, name: "Chilean Peso", code: "CLP" },
    { id: 30, name: "Bangladeshi Taka", code: "BDT" },
    { id: 31, name: "UAE Dirham", code: "AED" },
    { id: 32, name: "Egyptian Pound", code: "EGP" },
    { id: 33, name: "Saudi Riyal", code: "SAR" },
    { id: 34, name: "Qatari Rial", code: "QAR" },
    { id: 35, name: "Kuwaiti Dinar", code: "KWD" },
    { id: 36, name: "Omani Rial", code: "OMR" },
    { id: 37, name: "Bahraini Dinar", code: "BHD" },
    { id: 38, name: "Ghanaian Cedi", code: "GHS" },
    { id: 39, name: "Kenyan Shilling", code: "KES" },
    { id: 40, name: "Tanzanian Shilling", code: "TZS" },
    { id: 41, name: "Nigerian Naira", code: "NGN" },
    { id: 42, name: "Zambian Kwacha", code: "ZMW" },
    { id: 43, name: "Ugandan Shilling", code: "UGX" },
    { id: 44, name: "Rwandan Franc", code: "RWF" },
    { id: 45, name: "Central African CFA Franc", code: "XAF" },
    { id: 46, name: "West African CFA Franc", code: "XOF" },
    { id: 47, name: "East Caribbean Dollar", code: "XCD" },
    { id: 48, name: "Fiji Dollar", code: "FJD" },
    { id: 49, name: "Papua New Guinean Kina", code: "PGK" },
    { id: 50, name: "Samoan Tala", code: "WST" },
    { id: 51, name: "Tongan Paʻanga", code: "TOP" },
    { id: 52, name: "Armenian Dram", code: "AMD" },
    { id: 53, name: "Azerbaijani Manat", code: "AZN" },
    { id: 54, name: "Georgian Lari", code: "GEL" },
    { id: 55, name: "Kazakhstani Tenge", code: "KZT" },
    { id: 56, name: "Uzbekistani Som", code: "UZS" },
    { id: 57, name: "Kyrgyzstani Som", code: "KGS" },
    { id: 58, name: "Mongolian Tögrög", code: "MNT" },
    { id: 59, name: "Maldivian Rufiyaa", code: "MVR" },
    { id: 60, name: "Jamaican Dollar", code: "JMD" },
    { id: 61, name: "Haitian Gourde", code: "HTG" },
    { id: 62, name: "Cuban Peso", code: "CUP" },
    { id: 63, name: "Cuban Convertible Peso", code: "CUC" },
    { id: 64, name: "Dominican Peso", code: "DOP" },
    { id: 65, name: "Nicaraguan Córdoba", code: "NIO" },
    { id: 66, name: "Costa Rican Colón", code: "CRC" },
    { id: 67, name: "Panamanian Balboa", code: "PAB" },
    { id: 68, name: "Paraguayan Guarani", code: "PYG" },
    { id: 69, name: "Bolivian Boliviano", code: "BOB" },
    { id: 70, name: "Chilean Unidad de Fomento", code: "UF" },
    { id: 71, name: "Peruvian Sol", code: "PEN" },
    { id: 72, name: "Venezuelan Bolívar", code: "VES" }
]

export const BUSINESSES = [
    { id: 1, name: "Clothing Store" },
    { id: 2, name: "Electronics Store" },
    { id: 3, name: "Home Goods Store" },
    { id: 4, name: "Beauty Salon" },
    { id: 5, name: "Grocery Store" },
    { id: 6, name: "Fitness Center" },
    { id: 7, name: "Restaurant" },
    { id: 8, name: "Coffee Shop" },
    { id: 9, name: "Online Course Provider" },
    { id: 10, name: "Handmade Crafts" },
    { id: 11, name: "Pet Supplies" },
    { id: 12, name: "Jewelry Store" },
    { id: 13, name: "Art Gallery" },
    { id: 14, name: "Digital Marketing Agency" },
    { id: 15, name: "Travel Agency" },
    { id: 16, name: "Bookstore" },
    { id: 17, name: "Furniture Store" },
    { id: 18, name: "Florist" },
    { id: 19, name: "Car Dealership" },
    { id: 20, name: "Real Estate Agency" }
]

export const COUNTRIES = [
    { id: 1, name: "Afghanistan", code: "AF" },
    { id: 2, name: "Albania", code: "AL" },
    { id: 3, name: "Algeria", code: "DZ" },
    { id: 4, name: "Andorra", code: "AD" },
    { id: 5, name: "Angola", code: "AO" },
    { id: 6, name: "Antigua and Barbuda", code: "AG" },
    { id: 7, name: "Argentina", code: "AR" },
    { id: 8, name: "Armenia", code: "AM" },
    { id: 9, name: "Australia", code: "AU" },
    { id: 10, name: "Austria", code: "AT" },
    { id: 11, name: "Azerbaijan", code: "AZ" },
    { id: 12, name: "Bahamas", code: "BS" },
    { id: 13, name: "Bahrain", code: "BH" },
    { id: 14, name: "Bangladesh", code: "BD" },
    { id: 15, name: "Barbados", code: "BB" },
    { id: 16, name: "Belarus", code: "BY" },
    { id: 17, name: "Belgium", code: "BE" },
    { id: 18, name: "Belize", code: "BZ" },
    { id: 19, name: "Benin", code: "BJ" },
    { id: 20, name: "Bhutan", code: "BT" },
    { id: 21, name: "Bolivia", code: "BO" },
    { id: 22, name: "Bosnia and Herzegovina", code: "BA" },
    { id: 23, name: "Botswana", code: "BW" },
    { id: 24, name: "Brazil", code: "BR" },
    { id: 25, name: "Brunei", code: "BN" },
    { id: 26, name: "Bulgaria", code: "BG" },
    { id: 27, name: "Burkina Faso", code: "BF" },
    { id: 28, name: "Burundi", code: "BI" },
    { id: 29, name: "Cabo Verde", code: "CV" },
    { id: 30, name: "Cambodia", code: "KH" },
    { id: 31, name: "Cameroon", code: "CM" },
    { id: 32, name: "Canada", code: "CA" },
    { id: 33, name: "Central African Republic", code: "CF" },
    { id: 34, name: "Chad", code: "TD" },
    { id: 35, name: "Chile", code: "CL" },
    { id: 36, name: "China", code: "CN" },
    { id: 37, name: "Colombia", code: "CO" },
    { id: 38, name: "Comoros", code: "KM" },
    { id: 39, name: "Congo (Congo-Brazzaville)", code: "CG" },
    { id: 40, name: "Congo (Democratic Republic of the Congo)", code: "CD" },
    { id: 41, name: "Costa Rica", code: "CR" },
    { id: 42, name: "Croatia", code: "HR" },
    { id: 43, name: "Cuba", code: "CU" },
    { id: 44, name: "Cyprus", code: "CY" },
    { id: 45, name: "Czechia", code: "CZ" },
    { id: 46, name: "Denmark", code: "DK" },
    { id: 47, name: "Djibouti", code: "DJ" },
    { id: 48, name: "Dominica", code: "DM" },
    { id: 49, name: "Dominican Republic", code: "DO" },
    { id: 50, name: "Ecuador", code: "EC" },
    { id: 51, name: "Egypt", code: "EG" },
    { id: 52, name: "El Salvador", code: "SV" },
    { id: 53, name: "Equatorial Guinea", code: "GQ" },
    { id: 54, name: "Eritrea", code: "ER" },
    { id: 55, name: "Estonia", code: "EE" },
    { id: 56, name: "Eswatini", code: "SZ" },
    { id: 57, name: "Ethiopia", code: "ET" },
    { id: 58, name: "Fiji", code: "FJ" },
    { id: 59, name: "Finland", code: "FI" },
    { id: 60, name: "France", code: "FR" },
    { id: 61, name: "Gabon", code: "GA" },
    { id: 62, name: "Gambia", code: "GM" },
    { id: 63, name: "Georgia", code: "GE" },
    { id: 64, name: "Germany", code: "DE" },
    { id: 65, name: "Ghana", code: "GH" },
    { id: 66, name: "Greece", code: "GR" },
    { id: 67, name: "Grenada", code: "GD" },
    { id: 68, name: "Guatemala", code: "GT" },
    { id: 69, name: "Guinea", code: "GN" },
    { id: 70, name: "Guinea-Bissau", code: "GW" },
    { id: 71, name: "Guyana", code: "GY" },
    { id: 72, name: "Haiti", code: "HT" },
    { id: 73, name: "Honduras", code: "HN" },
    { id: 74, name: "Hungary", code: "HU" },
    { id: 75, name: "Iceland", code: "IS" },
    { id: 76, name: "India", code: "IN" },
    { id: 77, name: "Indonesia", code: "ID" },
    { id: 78, name: "Iran", code: "IR" },
    { id: 79, name: "Iraq", code: "IQ" },
    { id: 80, name: "Ireland", code: "IE" },
    { id: 81, name: "Israel", code: "IL" },
    { id: 82, name: "Italy", code: "IT" },
    { id: 83, name: "Jamaica", code: "JM" },
    { id: 84, name: "Japan", code: "JP" },
    { id: 85, name: "Jordan", code: "JO" },
    { id: 86, name: "Kazakhstan", code: "KZ" },
    { id: 87, name: "Kenya", code: "KE" },
    { id: 88, name: "Kiribati", code: "KI" },
    { id: 89, name: "Kuwait", code: "KW" },
    { id: 90, name: "Kyrgyzstan", code: "KG" },
    { id: 91, name: "Laos", code: "LA" },
    { id: 92, name: "Latvia", code: "LV" },
    { id: 93, name: "Lebanon", code: "LB" },
    { id: 94, name: "Lesotho", code: "LS" },
    { id: 95, name: "Liberia", code: "LR" },
    { id: 96, name: "Libya", code: "LY" },
    { id: 97, name: "Liechtenstein", code: "LI" },
    { id: 98, name: "Lithuania", code: "LT" },
    { id: 99, name: "Luxembourg", code: "LU" },
    { id: 100, name: "Madagascar", code: "MG" },
    { id: 101, name: "Malawi", code: "MW" },
    { id: 102, name: "Malaysia", code: "MY" },
    { id: 103, name: "Maldives", code: "MV" },
    { id: 104, name: "Mali", code: "ML" },
    { id: 105, name: "Malta", code: "MT" },
    { id: 106, name: "Marshall Islands", code: "MH" },
    { id: 107, name: "Mauritania", code: "MR" },
    { id: 108, name: "Mauritius", code: "MU" },
    { id: 109, name: "Mexico", code: "MX" },
    { id: 110, name: "Micronesia", code: "FM" },
    { id: 111, name: "Moldova", code: "MD" },
    { id: 112, name: "Monaco", code: "MC" },
    { id: 113, name: "Mongolia", code: "MN" },
    { id: 114, name: "Montenegro", code: "ME" },
    { id: 115, name: "Morocco", code: "MA" },
    { id: 116, name: "Mozambique", code: "MZ" },
    { id: 117, name: "Myanmar", code: "MM" },
    { id: 118, name: "Namibia", code: "NA" },
    { id: 119, name: "Nauru", code: "NR" },
    { id: 120, name: "Nepal", code: "NP" },
    { id: 121, name: "Netherlands", code: "NL" },
    { id: 122, name: "New Zealand", code: "NZ" },
    { id: 123, name: "Nicaragua", code: "NI" },
    { id: 124, name: "Niger", code: "NE" },
    { id: 125, name: "Nigeria", code: "NG" },
    { id: 126, name: "North Korea", code: "KP" },
    { id: 127, name: "North Macedonia", code: "MK" },
    { id: 128, name: "Norway", code: "NO" },
    { id: 129, name: "Oman", code: "OM" },
    { id: 130, name: "Pakistan", code: "PK" },
    { id: 131, name: "Palau", code: "PW" },
    { id: 132, name: "Palestine", code: "PS" },
    { id: 133, name: "Panama", code: "PA" },
    { id: 134, name: "Papua New Guinea", code: "PG" },
    { id: 135, name: "Paraguay", code: "PY" },
    { id: 136, name: "Peru", code: "PE" },
    { id: 137, name: "Philippines", code: "PH" },
    { id: 138, name: "Poland", code: "PL" },
    { id: 139, name: "Portugal", code: "PT" },
    { id: 140, name: "Qatar", code: "QA" },
    { id: 141, name: "Romania", code: "RO" },
    { id: 142, name: "Russia", code: "RU" },
    { id: 143, name: "Rwanda", code: "RW" },
    { id: 144, name: "Saint Kitts and Nevis", code: "KN" },
    { id: 145, name: "Saint Lucia", code: "LC" },
    { id: 146, name: "Saint Vincent and the Grenadines", code: "VC" },
    { id: 147, name: "Samoa", code: "WS" },
    { id: 148, name: "San Marino", code: "SM" },
    { id: 149, name: "Sao Tome and Principe", code: "ST" },
    { id: 150, name: "Saudi Arabia", code: "SA" },
    { id: 151, name: "Senegal", code: "SN" },
    { id: 152, name: "Serbia", code: "RS" },
    { id: 153, name: "Seychelles", code: "SC" },
    { id: 154, name: "Sierra Leone", code: "SL" },
    { id: 155, name: "Singapore", code: "SG" },
    { id: 156, name: "Slovakia", code: "SK" },
    { id: 157, name: "Slovenia", code: "SI" },
    { id: 158, name: "Solomon Islands", code: "SB" },
    { id: 159, name: "Somalia", code: "SO" },
    { id: 160, name: "South Africa", code: "ZA" },
    { id: 161, name: "South Korea", code: "KR" },
    { id: 162, name: "South Sudan", code: "SS" },
    { id: 163, name: "Spain", code: "ES" },
    { id: 164, name: "Sri Lanka", code: "LK" },
    { id: 165, name: "Sudan", code: "SD" },
    { id: 166, name: "Suriname", code: "SR" },
    { id: 167, name: "Sweden", code: "SE" },
    { id: 168, name: "Switzerland", code: "CH" },
    { id: 169, name: "Syria", code: "SY" },
    { id: 170, name: "Tajikistan", code: "TJ" },
    { id: 171, name: "Tanzania", code: "TZ" },
    { id: 172, name: "Thailand", code: "TH" },
    { id: 173, name: "Timor-Leste", code: "TL" },
    { id: 174, name: "Togo", code: "TG" },
    { id: 175, name: "Tonga", code: "TO" },
    { id: 176, name: "Trinidad and Tobago", code: "TT" },
    { id: 177, name: "Tunisia", code: "TN" },
    { id: 178, name: "Turkey", code: "TR" },
    { id: 179, name: "Turkmenistan", code: "TM" },
    { id: 180, name: "Tuvalu", code: "TV" },
    { id: 181, name: "Uganda", code: "UG" },
    { id: 182, name: "Ukraine", code: "UA" },
    { id: 183, name: "United Arab Emirates", code: "AE" },
    { id: 184, name: "United Kingdom", code: "GB" },
    { id: 185, name: "United States", code: "US" },
    { id: 186, name: "Uruguay", code: "UY" },
    { id: 187, name: "Uzbekistan", code: "UZ" },
    { id: 188, name: "Vanuatu", code: "VU" },
    { id: 189, name: "Vatican City", code: "VA" },
    { id: 190, name: "Venezuela", code: "VE" },
    { id: 191, name: "Vietnam", code: "VN" },
    { id: 192, name: "Yemen", code: "YE" },
    { id: 193, name: "Zambia", code: "ZM" },
    { id: 194, name: "Zimbabwe", code: "ZW" }
]